# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f731131963b21afdb4063dd07877cad977b0bc3f1762fc02ff5f50ff677718adb14abc68eb47ad69bea8973c36bc32cb689b8bf7bf715155e34a3a8e92cc6765

test:
  secret_key_base: 4e9902ad24f4fcf57d89b81bc98dae5f7c298f7406940233fa2b061ec3dc76b22f5fc8e3766ef84959958a389ed2de6e1b2064d4e763a9b2721328fa10e8588f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
